language: go
go:
  - "1.12.1"

services:
  - docker

notifications:
  email: false

env:
  - DEP_VERSION="0.5.0"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - go test -v -race ./...

after_success:
  - make docker-build

deploy:
  provider: script
  script: make deploy
  on:
    branch: master
