language: go
go:
  - "1.14.0"

services:
  - docker

notifications:
  email: false

script:
  - go test -v -race ./...

after_success:
  - make docker-build

deploy:
  provider: script
  script: make deploy
  on:
    branch: master
