language: go
go:
  - "1.12.x"

services:
  - docker

notifications:
  email: false

script:
  - env GO111MODULE=on go test -v -race ./...

after_success:
  - env GO111MODULE=on make docker-build

deploy:
  provider: script
  script: make deploy
  on:
    branch: master
